### ISSUE TITLE
Maybe run on github pages to save cost?

### ISSUE THREAD

**Issue by nurazhar** [tors/eosprice.io#1]
close
https://github.com/tors/eosprice.io/commit/e06c6bc4b0a4bd67e32023dc66ac16c296e64b15#commitcomment-24266142

**Comment by nurazhar** [comment]
i'm refering to this commit
https://github.com/tors/eosprice.io/commit/e06c6bc4b0a4bd67e32023dc66ac16c296e64b15

**Comment by tors** [comment]
@nurazhar i run the static site on s3. s3 costs are negligible. however, i have a server that caches eth prices, etc so I don't have to spam infura from the client side because maybe they will ban me if I get too many visitors. I'm just trying to be a good citizen :)
